### ISSUE TITLE
Be sure the collection is tested against 2.11 and contains sanity/ignore-2.12.txt if applicable

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ibm_zos_sysauto#7]
##### SUMMARY
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

If everything is OK, feel free to close the issue

**Comment by LUEDDEA** [comment]
Thanks @Andersson007. I will work on it.

**Comment by LUEDDEA** [comment]
we do not (yet) need ignore-*.txt

**Comment by Andersson007** [comment]
@LUEDDEA how about testing against 2.11?

**Comment by LUEDDEA** [comment]
@Andersson007 I did a manual test and will add it to the build pipeline

**Comment by Andersson007** [comment]
@LUEDDEA thanks!
